---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: webservers
  sudo: yes
  sudo_user: root
  remote_user: ubuntu

  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - base
    - db
    - web