---

- name: Provision a {{ application_name }} web server
  hosts: webservers
  sudo: yes
  sudo_user: root
  remote_user: inst743
   
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - base
    - db
    - web