- include:
    ../../common/tasks/grant_account_temp_permissions.yml

- name: Install Django Software
  shell: '{{ python_stack_pip_path }} install Django==1.6.5'
  remote_user: '{{ python_stack_non_priviledged_user }}'

# The django package that I uploaded was already configured and
# tested with Gunicorn before I canned it. With over 20 examples
# already (even if each took just 3 minutes), we are out of time.
# Instead of having to back out a compressed file, I am just adding
# gunicorn for now.
- name: Install Gunicorn (not currently used)
  shell: '{{ python_stack_pip_path }} install gunicorn==19.0.0'
  remote_user: '{{ python_stack_non_priviledged_user }}'

- name: Upload Django's manage.py
  copy:
    src: manage.py
    dest: '/home/{{ python_stack_non_priviledged_user }}/sample_project/manage.py'
    owner: '{{ python_stack_non_priviledged_user }}'
    group: '{{ python_stack_non_priviledged_user }}'
    mode: 0600
  sudo: yes

- name: Upload Initial Django (tiny) Deployment
  copy:
    src: sample_project_django.tar
    dest: '/home/{{ python_stack_non_priviledged_user }}/sample_project/sample_project_django.tar'
    owner: '{{ python_stack_non_priviledged_user }}'
    group: '{{ python_stack_non_priviledged_user }}'
    mode: 0600
  sudo: yes

- name: Extract virtualenv source code
  shell: 'cd /home/{{ python_stack_non_priviledged_user }}/sample_project; tar -xvf sample_project_django.tar'
  remote_user: '{{ python_stack_non_priviledged_user }}'

- name: Clean-up Django delivery tarball
  command: /bin/rm /home/{{ python_stack_non_priviledged_user }}/sample_project/sample_project_django.tar
  remote_user: '{{ python_stack_non_priviledged_user }}'

- include:
    ../../common/tasks/revoke_account_temp_permissions.yml
